### ISSUE TITLE
Missing pages when using single .exe file

### ISSUE THREAD

**Issue by AndreReisAntunes** [plotly/dash-labs#115]
Hi,

I've a working da-sh app with multi-page using the single file per folder method. Works fine but when I convert it to an executable using py setup.py the app does not detect the pages folder and so my pages are not shown in the dash app.

Could you advice any specific requirements for the multipage pages folder to be included ?

**Comment by AnnMarieW** [comment]
Hi @AndreReisAntunes 

Thanks for raising this issue.   I see you also posted this question on the forum, and that will be the best place to get an answer.  

Since the `pages` feature is now part of Dash and is no longer being developed in dash-labs, I'm going to close this issue.  If this is a bug, we can re-open the issue with more details and a minimal example in the dash repo.
