### ISSUE TITLE
Figure Templates

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash-labs#15]
I'm a big fan of  Dash Labs and one of my favorite features is the way it generates the figure templates.  It inspired me to create a new library of Bootstrap themed figure templates that can be used with any version of Dash.  See the forum post [here](https://community.plotly.com/t/dash-bootstrap-templates/52456)

When I was working on this project,  I noticed that the Dash Labs figure templates updates the colorways, but not the colorscales.  Those remain the `Plasma` default regardless of the Bootstrap theme selected.  Also the geo figures have a black background based on the `plotly_dark` figure template.

You can see it using this [demo app](https://github.com/AnnMarieW/dash-bootstrap-templates/blob/main/examples/dl_demo_4figures.py):  

This is the current dash labs figure template for the `Slate` theme

![image](https://user-images.githubusercontent.com/72614349/116438640-7e2a4600-a803-11eb-8045-d07f8ee59f3e.png)

This is an updated template from the `dash-bootstrap-templates` library  See more [here](https://hellodash.pythonanywhere.com/dash_labs)

![image](https://user-images.githubusercontent.com/72614349/116015365-cec85600-a5ed-11eb-8c33-e25495eced9d.png)

Would you like a pull request to update the dash-labs templates for the geo figures and the colorscales, or do you prefer to keep this type of change in a third party library?

**Comment by jonmmease** [comment]
Thanks for the report @AnnMarieW, The use of the dark geo theme is definitely an oversite.

As for the colorscales, how did you go about generating them?  In general, I'm personally pretty hesitant about creating custom continuous colorscales due to the complex perceptual uniformity considerations. See writeups like https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html.

There's already a bit of custom logic in the template generation to improve the visual separation of the categorical colorways, so I'm certainly not opposed to the idea of generating a colorscale from the theme as well, I would just want to make sure we're doing something that's visually accurate in addition to looking nice with the template.  Does that make sense?

**Comment by AnnMarieW** [comment]
Thanks, for the link to article - that was very interesting.  I suspected there was more to creating a good continuous colorscale than just making something that  looked pretty :slightly_smiling_face: 


I used 10 scales to be consistent with the other built-in Plotly colorscales.  Then used the first two colors of the colorways, `primary` and `danger` ,  and brightened the  `danger` color with the spectra function.


```
def get_colorscale(color1, color2):
   # A range between 'primary' and 'warning'
    color1=spectra.html(color1)
    color2=spectra.html(color2).brighten(20)

    scale = np.linspace(0, 1, 11)
    theme_swatches = spectra.range([color1, color2], 11)
    return [[k,v.hexcode] for k,v in zip(scale,theme_swatches)]
```





For the geo, I added a function to check the lightness of the theme's background color before selecting the base template.  I did it this way in case there were other figure that might have the same issue.

```
def get_template(bg_color):
    # spectra.lab(L, a, b)   L is lightness from 0 to 100
    lightness =spectra.html(bg_color).to("lab").values[0]
    if lightness < 50:
        return copy.deepcopy(pio.templates["plotly_dark"])
    else:
        return copy.deepcopy(pio.templates["plotly_white"])
```
