### ISSUE TITLE
Multi Page Apps: Documentation

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/dash-labs#63]
In the reference [section of chapter 8](https://github.com/plotly/dash-labs/blob/main/docs/08-MultiPageDashApp.md#reference), the `description` prop, between `title` and `image`, needs to be fully written out. Currently it says:
`description`: The . If not supplied, then nothing is supplied.

**Comment by AnnMarieW** [comment]
Hi @Coding-with-Adam 

Thanks for reporting!  The text is not showing because it contains code that needs to be enclosed in backticks.  Here's the text with the backticks included around the `<meta type="description"></meta>`:
- `description`:
   The `<meta type="description"></meta>`.
   If not supplied, then nothing is supplied.

I noticed that the backticks were missing in a few other places as well.  Chapter 8,9,10 needs to be reviewed
