### ISSUE TITLE
Multi-Page Apps: Location of pages directory

### ISSUE THREAD

**Issue by eiriklid** [plotly/dash-labs#84]
It seems that plugin.pages expects current working to contain pages, so they can be imported like. `from pages.my_page import layout.`
However the company I work for require the structure of the project to be like: `from <src-directory>.pages.my_page import layout`.
Is there any way to accommodate this currently or would it need a PR?

**Comment by AnnMarieW** [comment]
HI @eiriklid,
Thanks for reporting, and yes, this would need a PR.  Do you have the assets folder set up in the same way?  If so, this is  [fixed in the pending PR](https://github.com/plotly/dash/blob/d304e67ac79cf833e88e1b25daa459f4e9bb03c2/dash/dash.py#L366) in Dash.  It also makes it possible to change the name of the directory so it doesn't have to be called "pages".   

I hope this will be available in dash fairly soon, but if it looks like there will be a delay, I'll see if I can make at least the pages relative to the root directory available in dash-labs.  (The ability to change the name of the pages directory will require a change to dash)

**Comment by eiriklid** [comment]
Thanks for the reply @AnnMarieW! Yes the assets folder is set up the same way and we set the location when creating the Dash object. 
We solved it by hard-coding the path, so we can wait for the pending PR to be merged and released :)

I love the pages setup btw, great work!

Should we close the issue now or after the PR?
